language: python
python:
  - '3.8.1'

services:
  - docker

before_script: pip install docker-compose

script:
  - .devcontainer/docker-compose run app sh -c 'cd app_project && python manage.py test'
